development:
  adapter: postgresql
  encoding: utf-8
  database: development
  pool: 5

test:
  adapter: postgresql
  encoding: utf-8
  database: development
  pool: 5

production:
  adapter: postgresql
  encoding: utf-8
  database: development
  pool: 5